name: CI

on: [pull_request, push]

jobs:
  linux:
    name: Test on Ubuntu (Elixir ${{ matrix.elixir_version }}, OTP ${{ matrix.otp_version }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir_version: ['1.8.2', '1.9.4', '1.10.3']
        otp_version: ['20.3', '21.3', '22.3']
        exclude:
          - elixir_version: '1.10.3'
            otp_version: '20.3'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir_version }}
          otp-version: ${{ matrix.otp_version }}
      - name: Restore deps and _build
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ matrix.elixir_version }}-${{ matrix.otp_version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Restore plts
        uses: actions/cache@v2
        with:
          path: test/support/plts
          key: ${{ runner.os }}-dialyzer-${{ matrix.elixir_version }}-${{ matrix.otp_version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - run: mix deps.get
      - run: MIX_ENV=test mix deps.compile
      - run: MIX_ENV=test mix compile --warnings-as-errors
      - run: MIX_ENV=test mix credo --strict
      - name: Check if formatted
        if: ${{ contains(matrix.elixir_version, '1.10') }}
        run: mix format --check-formatted
      - name: Dialyzer
        run: mix dialyzer --halt-exit-status
      - run: MIX_ENV=test mix coveralls.github
